# ===== CONFIGURACIÓN PARA DB=====
# detecta estos nombres y los reemplaza
MYSQLHOST = 'MYSQLHOST'
MYSQLUSER = 'MYSQLUSER'
MYSQLPASSWORD = 'MYSQLPASSWORD' 
MYSQLDATABASE = 'MYSQLDATABASE'
MYSQLPORT = 'MYSQLPORT'
MYSQLCHARSET = 'utf8mb4'
