"""
# ===== CONFIGURACIÓN SMTP =====
# Configuración SendGrid para PROYECTO-SENA

from .conexion_email import (
    SMTP_SERVER, SMTP_PORT, SMTP_USERNAME, 
    SMTP_PASSWORD, MAIL_DEFAULT_SENDER, MAIL_DEFAULT_SENDER_NAME
)

"""
# ===== CONFIGURACIÓN SMTP DESPLIEGUE =====
import os

SMTP_SERVER = os.environ['SMTP_SERVER']
SMTP_PORT = int(os.environ['SMTP_PORT'])
SMTP_USERNAME = 'apikey'
SMTP_PASSWORD = os.environ['SENDGRID_API_KEY']
MAIL_DEFAULT_SENDER = os.environ['MAIL_DEFAULT_SENDER']
MAIL_DEFAULT_SENDER_NAME = os.environ['MAIL_DEFAULT_SENDER_NAME']
